// This Playground was generated by the SPI-Playgrounds app, which is part of the
// Swift Package Index (https://swiftpackageindex.com), using 🏟 Arena
// (https://github.com/finestructure/arena) to import the dependency.
//
// For more information about the SPI-Playgrounds app and to download it, visit
// https://swiftpackageindex.com/try-in-a-playground

import RxSwift

let disposeBag = DisposeBag()

Observable.of("🐶", "🐱", "🐭", "🐹")
    .subscribe(onNext: { element in
        print(element)
    })
    .disposed(by: disposeBag)

//: [Next](@next)
